<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Towja baza danych jest nieaktualna, uaktualnij j� do najnowszej wersji',
  'Your version' => 'Twoja wersja',
  'Latest version' => 'Najnowsza wersja',
  'phplist version' => 'Wersja <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'Baza danych nie zosta�a zainicjowana',
  'go to' => 'id� do',
  'Initialise Database' => 'inicjuj� baz� danych',
  'to continue' => 'aby kontynuowa�',
  'A new version of PHPlist is available!' => 'Nowa wersja PHPlist jest dost�pna!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'Nowa wersja mo�e poprawi� kwesti� bezpiecze�stwa,<br/>wi�c zalecamy uaktualni� najszybciej jak to mo�liwe',
  'View what has changed' => 'Zobacz co zosta�o zmienione',
  'Download' => 'Pobierz',
  'System Functions' => 'Funkcje systemu',
  'Setup ' => 'Ustawienia ',
  'Check Database structure' => 'Sprawd� struktur� bazy danych',
  'View the eventlog' => 'Przegl�daj dziennik zdarze�',
  'Configuration functions' => 'Funkcje konfiguracji',
  'Configure Attributes' => 'Ustawienia atrybut�w',
  'Control values for' => 'Ustawienia warto�ci dla',
  'Control values for' => 'Ustawienia warto�ci dla',
  'Control values for' => 'Ustawienia warto�ci dla',
  'Configure Subscribe pages' => 'Ustawienia stron rejestracji',
  'List and user functions' => 'Funkcje list i u�ytkownika',
  'List the current lists' => 'Wy�wietl obecne listy',
  'List all Users' => 'Wy�wietl wszystkich u�ytkownik�w',
  'Reconcile the user database' => 'Operacje na bazach u�ytkownik�w',
  'Import Users' => 'Import u�ytkownik�w',
  'Export Users' => 'Eksport u�ytkownik�w',
  'Administrator functions' => 'Funkcje administratora',
  'Add, edit and remove Administrators' => 'Dodaj, edytuj i usu� Administrator�w',
  'Configure attributes for administrators' => 'Konfiguruj atrybuty Administrator�w',
  'Message functions' => 'Funkcje wiadomo�ci',
  'Configure Templates' => 'Funkcje szablon�w',
  'List all Messages' => 'Wy�wietl wszystkie wiadomo�ci',
  'Process the Message queue' => 'Przetwarzaj kolejk� wiadomo�ci',
  'RSS Functions' => 'Funkcje kana��w RSS',
  'Get RSS feeds' => 'Pobierz kana�y RSS',
  'View RSS items' => 'Wy�wietla elementy RSS',
  'Plugins' => 'Dodatki',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Zmie� swoje ustawienia (np. has�o)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Ustawi�e� TEST w config.php na 1, wi�c b�dzie tylko pokazane co zosta�oby wys�ane',

  # added at a later stage
  'setup' => 'ustawienia',
  'upgrade' => 'uaktualnij',
  'dbcheck' => 'baza',
  'eventlog' => 'dziennik zdarze�',
  'attributes' => 'atrybuty',
  'spage' => 'strona rejestracji',
  'list' => 'listy',
  'reconcileusers' => 'uzgadnianie u�ytkownik�w',
  'import' => 'import',
  'export' => 'eksport',
  'admins' => 'administratorzy',
  'adminattributes' => 'atrybuty admina',
  'send' => 'wy�lij',
  'templates' => 'szablony',
  'processqueue' => 'kolejka wiadomo�ci',
  'processbounces' => 'kolejka zwrot�w',
  'getrss' => 'pobierz rss',
  'viewrss' => 'zobacz rss',
  'admin' => 'admin',
  'preparesend' => 'przygotuj wysy�k�',
  'sendprepared' => 'wy�lij przygotowane',


);

?>