<?php
$lan = array(
  "Import emails from IMAP folders" => "Import adres�w email z folder�w IMAP",
  "No lists available" => "Brak dost�pnych list",
  "Add a list" => "Dodaj list�",
  "personal" => "prywatny",
  "email" => "email",
  "folder" => "folder",
  "date" => "data",
  "can't connect" => "nie mo�na po��czy� si�",
  "Processing" => "Przetwarzanie",
  "messages" => "wiadomo�ci",
  "done" => "gotowe",
  "imap_getmailboxes failed" => "b��d imap_getmailboxes",
  "Please enter details of the IMAP account" => "Wprowad� detale konta IMAP",
  "Select the headers fields to search" => "Wybierz nag��wki p�l wyszukiwania",
  "Select the lists to add the emails to" => "Wybierz listy, aby doda� adresy email",
  "Adding users to list" => "Dodawanie u�ytkownik�w do listy",
  "Mark new users as HTML" => "Oznacz nowych u�ytk. jako HTML",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "Je�li zaznaczysz",
  "Overwrite Existing" => "Nadpisz istniej�ce",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "informacje o u�ytkowniku w bazie danych zostan� zast�pione importowanymi informacjami. U�ytkownicy s� dopasowywani po adreseie email.",
  "Only use complete addresses" => "Tylko pe�ne adresy",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "adresy, kt�re nie posiadaj� prawdziwej nazwy zostan� zignorowane. Je�li nie zaznaczysz tej opcji wszystkie adresy b�d� importowane.",
  "If you choose" => "Je�li wybierzesz",
  "send notification email" => "wy�lij potwierdzenie",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "u�ytkownicy, kt�rych dodajesz otrzymaj� pro�b� o potwierdzenie rejestracji, na kt�re b�d� musieli odpowiedzie�. Jest to zalecane, bo dzi�ki temu b�dzie mo�na zidentyfikowa� nieprawid�owe adresy email.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Wy�lij potwierdzenie",
  "Make confirmed immediately" => "Oznacz u�ytkownik�w jako potwierdzonych",
  "import3info" => "Istniej� dwie mozliwo�ci dodania nazw u�ytkownik�w:
 albo jeden atrybut dla ca�ej nazwy albo dwa atrybuty, jeden dla imienia i jeden dla nazwiska. 
Je�li u�yjesz 'dw�ch atrybut�w', nazwa zostanie podzielona po pierwszej spacji.",
  "Use one attribute for name" => "U�yj jednego atrybutu dla nazwy",
  'Use two attributes for the name' => 'U�yj dw�ch atrybut�w dla nazwy',
  "Attribute one" => "Pierwszy atrybut",
  "Create Attribute" => "Utw�rz atrybut",
  "Attribute two" => "Drugi atrybut",
  "Cannot continue" => "Nie mo�na kontynuowa�",
  "ok" => "ok",
  "failed" => "b��d",
  "Processed" => "Przetworzono",
  "folders and" => "pliki oraz",
  "unique emails found" => "znaleziono pojedyncze adresy email",
  "list" => "lista",
  "lists" => "listy",
  "new email was" => "nowy adres email",
  "new emails were" => "nowe adresy email",
  "email was" => "adres by�",
  "emails were" => "adres�w by�o",
  "All the emails already exist in the database and are members of the" => "Wszystkie adresy email istniej� ju� w bazie i s� cz�onkami",
  "succesfully imported to the database and added to" => "z sukcesem zaimportowano do bazy i dodano do",
  "subscribed to the" => "zasubskrybowano do",
  "emails already existed in the database" => "adresy email ju� istniej� w bazie",
  "Invalid Emails found." => "Znaleziono nieprawid�owe adresy email.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "Rekordy zosta�y dodane ale adresy email zosta�y wygenerowane. Aby je znale�� poszukaj",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "Rekordy zosta�y usuni�te. Sprawd� �r�d�o i zaimportuj dane ponownie. Duplikaty zostan� wykryte.",
  "No emails found" => "Nie znaleziono adres� email",
  "Import some more emails" => "Zaimportuj wi�cej adres�w email",
  'Server' => 'Serwer',
  'User' => 'U�ytkownik',
  'Password' => 'Has�o',
  'Continue' => 'Kontynuuj',
  'Process Selected Folders' => 'Przetwarzaj wybrane foldery',
);
?>