<?php
$lan = array(
 'Please select a message to display' => 'Wybierz wiadomo�� do wy�wietlenia',
 'Attachments for this message' => 'Za��czniki tej wiadomo�ci',
 'No attachments' => 'Brak za��cznik�w',
 'Filename' => 'Nazwa pliku',
 'Size' => 'Rozmiar',
 'Mime Type' => 'Typ Mime',
 'Description' => 'Opis',
 'Lists this message has been sent to' => 'Ta wiadomo�� zosta�a wys�ana do nast. list',
 'None yet' => 'None yet',
 'Send this (same) message to (a) new list(s)' => 'Wy�lik t� sam� wiadomo�� do kolejnych list',
 'List is Active' => 'Lista jest aktywna',
 'List is not Active' => 'Lista jest nieaktywna',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Uwaga:</b> ta wiadomo�c zosta�a ju� wys�ana do wszystkich list. Aby wys�a� j� ponownie do nowych u�ytkownik�w u�yj funkcji "Kolejkuj ponownie"',
 'Resend' => 'Wy�lij ponownie',
 'id' => 'id',
 'subject' => 'temat',
 'fromfield' => 'pole od',
 'tofield' => 'pole do',
 'replyto' => 'odpowied� do',
 'message' => 'wiadomo��',
 'textmessage' => 'wiadomo�� tekstowa',
 'footer' => 'stopka',
 'entered' => 'wprowadzono',
 'modified' => 'zmodyfikowano',
 'embargo' => 'ograniczenie do',
 'repeatinterval' => 'interwa� powt�rze�',
 'repeatuntil' => 'powtarzaj do',
 'status' => 'status',
 'userselection' => 'wyb�r u�ytkownika',
 'sent' => 'wys�ano',
 'htmlformatted' => 'sformatowano w html',
 'sendformat' => 'format wysy�ania',
 'template' => 'szablon',
 'processed' => 'przetworzono',
 'astext' => 'jako tekst',
 'ashtml' => 'jako html',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'aspdf' => 'jako pdf',
 'astextandpdf' => 'jako text i pdf',
 'viewed' => 'wy�wietlano',
 'bouncecount' => 'liczba zwrot�w',
 'sendstart' => 'pocz�tek wysy�ania',
 'rsstemplate' => 'szablon RSS',
 'owner' => 'w�a�ciciel',

 # new in 2.10.1
 'edit this message' => 'Edytuj t� wiadomo��',
);
?>
