<?php 
$lan = array(
  "NoRecord" => "Nie ma takiego rekordu",
  "BackToBList" => "Powr�t do listy zwrot�w",
  "NotFound" => "Nie znaleziono<br/>",
  "AddedToB" => "Dodano %s do liczby zwrot�w dla u�ytkownika %s<br/>",
  "NotAddedToB" => "Nie mo�na doda� %s do liczby zwrot�w dla u�ytkownika %s<br/>",
  "MadeUnconfirmed" => "Oznaczono u�ytkownika %s jako niepotwierdzony<br/>",
  "MadeUserRText" => "U�ytkownikowi %s w��czono odbieranie wiadomo�ci tekstowych<br/>",
  "DelUser" => "Usuni�to u�ytkownika %s<br/>",
  "DeletingB" => "Usuwam zwroty %s .. <br>",
  "DoneAndLoading" => "..Gotowe, �aduj� nast�pny zwrot..",
  "NoSRecord" => "Nie ma takiego rekordu",
  "PossibleActions" => "Mo�liwe dzia�ania:",
  "ForUser" => "Dla u�ytkownika o adresie e-mail",
  "IncreaseB" => "Zwiekszenie licznika zwrot�w o",
  "IncreaseBNote" => "(u�yj liczby ujemnej aby zmniejszy�)",
  "MarkAsUnconfirmed" => "Oznacz u�ytkownika jako nipotwierdzony",
  "MarkAsUnconfirmedNote" => "(a zatem mo�esz ponownie wys�a� pro�b� o potwiedzenie)",
  "SetReceiveText" => "Wysy�aj u�ytkownikowi wiadomo�ci tekstowe zamiast HTML",
  "DelUser1" => "Usu� u�ytkownika",
  "DelAndGo" => "Usu� ten zwrot i przejd� do nast�pnego",
  "DoAbove" => "Wykonaj powy�sze",
  "BounceDetails" => "Detale zwrotu:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Status",
  "Comment" => "Komentarz",
  "Header" => "Nag��wek",
  "Body" => "Zawarto��",
  
  # new in 2.9.5
  'Regular Expression' => 'Wyra�enie regularne',
  'Action' => 'Dzia�anie',
  'Memo for this rule' => 'Notatka dla tej regu�y',
  'Add new Rule' => 'Dodaj now� regu��',
  'Create New Rule based on this bounce' => 'Utw�rz now� regu�� na podstawie tego zwrotu',
);
?>