<?php
$lan = array( 
 'checklist for installation' => 'Lista kontrolna dla instalacji',
 'cannot be empty' => 'nie mo�e byc puste',
 'editing' => 'Edytuj�',
 'save changes' => 'Zapisz zmiany',
 'edit' => 'edycja',

   # added 24 May 2006
  'delete user' => 'usu� u�ytkownika',
  'unconfirm user' => 'anuluj potwierdzenie',
  'blacklist user' => 'dodaj do czarnej listy',
  'delete user and bounce' => 'usu� u�ytkownika i odrzucenia',
  'unconfirm user and delete bounce' => 'anuluj potwierdzenie i usu� odrzucenia',
  'blacklist user and delete bounce' => 'dodaj do czarnej listy i usu� odrzucenia',
  'delete bounce' => 'usu� odrzucenia',
  'Website address (without http://)' => 'Adres strony (bez http://)',
  'Domain Name of your server (for email)' => 'Nazwa domeny Twojego serwera (dla email)',
  'Person in charge of this system (one email address)' => 'Osoba odpowiedzialna za ten system (jeden adres email)',
  'How often do you want to check for a new version of PHPlist (days)' => 'Jak cz�sto chcesz sprawdza� czy jest nowa wersja PHPlist (dni)',
  'List of people to CC in system emails (separate by commas)' => 'Lista os�b DW w systemie mailingowym (oddzielone przecinkami)',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Kto otrzymuje raporty (adres emial, oddziel wile adres�w przecinakmi)',
  'From email address for system messages' => 'Adres emial w polu OD dla wiadomo�ci systemowych',
  'What name do system messages appear to come from' => 'Z jak� nazw� maj� przychodzi� wiadomo�ci systemowe',
  'Reply-to email address for system messages' => 'Adres Reply-to dla wiadomo�ci systemowych',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'je�li jest widoczna tylko jedna  lista, czy powinna by� ukryta na sronie i automatycznie
    rozes�a� do zarejestrowanych u�ytkownik�w (0/1)',
  'width of a textline field (numerical)' => 'szeroko�� pola tekstowego (liczba)',
  'dimensions of a textarea field (rows,columns)' => 'wymiary pola obszaru tekstowego (wiersze,kolumny)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'Czy admin powinien otrzymywa� kopie wiadomo�ci rejestruj�cych, wyrejestruj�cych oraz aktualizacyjnych (0/1)',
  'The default subscribe page when there are multiple' => 'Domy�lna strona rejestrowania (je�li jest kilka)',
  'The default HTML template to use when sending a message' => 'Domy�lny szablon HTML u�ywany podczas rozsy�ania wiadomo�ci',
  'URL where users can subscribe' => 'URL gdzie u�ytkownicy mog� si� rejestrowa�',
  'URL where users can unsubscribe' => 'URL gdzie u�ytkownicy mog� si� wyrejestrowa�',
  'URL where users have to confirm their subscription' => 'URL gdzie u�ytkownicy musz� potwierdzi� swoj� rejestracj�',
  'URL where users can update their details' => 'URL gdzie u�ytkownicy mog� aktualizowa� swoje dane',
  'URL where messages can be forwarded' => 'URL gdzie wiadomo�ci mog� by� przekazywane',
  'Subject of the message users receive when they subscribe' => 'Temat wiadomo�ci, kt�r� otrzymuj� u�ytkownicy gdy sie rejestruj�',
  'Message users receive when they subscribe' => 'Wiadomo��, kt�r� otrzymuj� u�ytkownicy gdy si� rejestruj�',
  'Subject of the message users receive when they unsubscribe' => 'Temat wiadomo�ci, kt�r� otrzymuj� u�ytkownicy gdy sie wyrejestrowuj�',
  'Message users receive when they unsubscribe' => 'Wiadomo��, kt�r� otrzymuj� u�ytkownicy gdy si� wyrejestrowuj�',
  'Subject of the message users receive after confirming their email address' => 'Temat wiadomo�ci, kt�r� otrzymuj� u�ytkownicy po potwierdzeniu rejestracji',
  'Message users receive after confirming their email address' => 'Wiadomo�� kt�r� otrzymuj� u�ytkownicy po potwierdzeniu rejestracji',
  'Subject of the message users receive when they have changed their details' => 'Temat wiadomo�ci, kt�r� u�ytkowincy otrzymuj� gdy aktualizuj� swoje dane',
  'Message that is sent when users change their information' => 'Wiadomo��, kt�r� u�ytkowincy otrzymuj� gdy aktualizuj� swoje dane',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'Cz�� wiadomo�ci, kt�ra jest wysy�ana na nowy adres email gdy u�ytkownicy uaktualniaj� swoje dane i gdy zosta� zmieniony ich adres email',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'Cz�� wiadomo�ci, kt�ra jest wysy�ana na stary adres email gdy u�ytkownicy uaktualniaj� swoje dane i gdy zosta� zmieniony ich adres email',
  'Subject of message to send when users request their personal location' => 'Temat wiadomo�ci wysy�anej do u�ytkownik�w gdy za��daj� osobistej lokalizacji',
  'Message to send when they request their personal location' => 'Wiadomo�� wysy�ana do u�ytkownik�w gdy za��daj� osobistej lokalizacji',
  'Default footer for sending a message' => 'Domyslna stopka dla wysy�anych wiadomo�ci',
  'Footer used when a message has been forwarded' => 'Stopka u�ywana gdy wiadomo�� jest przesy�ana',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'Nag��wek stron publicznych. Nag��wek powinien zaczyna� si� od &lt;/head&gt; . Mo�esz doda� elementy nag��wka, alen ie dodawaj tytu�u ani innych podstawowych element�w nag��wka.',
  'Footer of public pages' => 'Stopka stron publicznych',
  'Charset for HTML messages' => 'Zestaw znak�w dla stron HTML',
  'Charset for Text messages' => 'Zestaw znak�w dla wiadomo�ci tekstowych',
  'CSS for HTML messages without a template' => 'CSS dla wiadomo�ci HTML bez szablonu',
  'Domains that only accept text emails, one per line' => 'Domeny, kt�re akceptuj� tylko wiadomo�ci tekstowe (jeden wpis w jednej linii)',
  'Minimum amount of items to send in an RSS feed' => 'Minimalna ilo�� element�w wysy�anych w kanale RSS',
  'Template for text item in RSS feeds' => 'Szablon dla element�w tekstowych kana�u RSS',
  'Template for HTML item in RSS feeds' => 'Szablon dla element�w HTML kana�u RSS',
  'Maximum amount of items to send in an RSS feed' => 'Maksymalna ilo�� element�w wysy�anych w kanale RSS',
  'Template for separator between feeds in RSS feeds (text)' => 'Szablon dla separatora w kanale RSS (text)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Szablon dla separatora w kanale RSS (HTML)',
  'Width in px of FCKeditor Area' => 'Szeroko�� w pikselach obszaru edytora FCKeditor',
  'Height in px of FCKeditor Area' => 'Wysoko�� w pikselach obszaru edytora FCKeditor',
);
?>