<?php 
$lan = array(

  'add_list' => 'Dodaj list�', //duplicated in import1_text
  'cant_connect' => 'nie mo�na po��czy� si� z baz� danych',
  'no_users_to_copy' => 'Brak u�ytkownik�w do skopiowania, czy przedrostek jest prawidowy?',
  'remote_server' => 'Wprowad� detale zdalnego serwera',
  'server' => 'Serwer:',
  'user' => 'U�ytkownik:',
  'passwd' => 'Has�o:',
  'database' => 'Nazwa bazy danych:',
  'table_prefix' => 'Przedrostek tabeli:',
  'usertable_prefix' => 'Przedrostek tabeli u�ytkownika:',
  'select_lists' => 'Wybierz listy aby doda� adresy',
  'copy_lists' => 'Kopiuj listy ze zdalnego serwera (listy s� dopasowywane po nazwie)',
  'users_as_html' => 'Oznacz nowych u�ytk. jako HTML:',
  'info_overwrite_existing' => 'Je�li zaznaczysz "Nadpisz istniej�ce", informacje o u�ytkowniku w bazie danych zostan� zast�pione importowanymi informacjami. U�ytkownicy s� dopasowywani po adreseie email.',
  'overwrite_existing' => 'Nadpisz istniej�ce:',
  'connecting_remote' => 'Tworzenie po��czenie ze zdaln� baz� danych',
  'getting_data' => 'Pobieranie danych z ',
  'remote_version' => 'Wersja zdalnej bazy',
  'remote_has' => 'Zdalna baza ma',
  'users' => 'u�ytkownik�w',
  'lists' => 'list',
  'copying_lists' => 'Kopiowanie list',
  'list' => 'Lista',
  'exists_locally' => 'istnieje lokalnie',
  'created_locally' => 'utworzono lokalnie',
  'remote_list' => 'Zdalna lista',
  'not_created' => 'nie utworzono',
  'copying_attribs' => 'Kopiowanie atrybut�w',
  'attrib' => 'Atrybut',
  'copying_users' => 'Kopiowanie u�ytkownik�w',
  'overwrite_local' => 'nadpisywanie danych lokalnych',
  'keep_local' => 'zachowywanie danych lokalnych',
  'new_user' => 'jest nowym u�ytkownikiem',
  'no_mapped_attrib' => 'B��d, brak zamapowanych atrybut�w dla',
  'no_local_list' => 'B��d, nie zdefiniowano list lokalnych dla',
  'No lists available' => 'Brak dost�pnych list',
  'Done' => 'Gotowe',
  'new users' => 'nowych u�ytkownik�w',
  'and' => 'oraz',
  'existing users' => 'istniej�cych u�ytkownik�w',
  'continue' => 'Kontynuuj',

);
?>