<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Nie posiadasz wystarczaj�cych uprawnie� aby wy�wietli� t� stron�',
  'Add a user' => 'dodaj u�ytkownika',
  'add user' => 'Dodaj u�ytkownika',
  'Members of' => 'Cz�onkowie',
  'Tag all users in this page' => 'Zaznacz wszystkich u�ytkownik�w na tej stronie',
  'back to this list' => 'powr�t do listy',
  'Download users on this list as a CSV file' => 'Pobierz u�ytkownik�w tej listy do pliku CSV',
  'Please enter a listid' => 'Wprowad� identyfikator listy',
  'Processing' => 'Przetwarzam',
  'users were moved to' => 'u�ytkownicy zostali przeniesieni do',
  'users were copied to' => 'u�ytkownicy zostali skopiowani do',
  'users were deleted from this list' => 'u�ytkownicy zostali usuni�ci z tej listy',
  'Users found, click add to add this user' => 'Znaleziono u�ytkownik�w, kliknij Dodaj aby doda� u�ytkownika',
  'Add' => 'Dodaj',
  'No user found with that email' => 'Nie znaleziono u�ytkownik�w z tym adresem email',
  'Inserting user' => 'Wstawianie u�ytkownika',
  'User added' => 'U�ytkownik dodany',
  'Deleting' => 'Usuwanie',
  'Done' => 'Gotowe',
  'Users on this list' => 'U�ytkownik�w na tej li�cie',
  'Listing user' => 'Wy�wietl u�ytkownika',
  'to' => 'do',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Wy�wietl u�ytkownik�w 1 do 50',
  'Members' => 'Cz�onkowie',
  'confirmed' => 'potwierdzony',
  'tag' => 'oznacz',
  'del' => 'usu�',
  'Delete'=>'Usu�',
  '# msgs' => '# wiad.',
  '# rss' => '# rss',
  'rss freq' => 'cz�stotliwo�� rss',
  'last sent' => 'ostatnio wys�ano',
  'What to do with "Tagged" users' => 'Co zrobi� z oznaczonymi u�ytkownikami',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Przetworzeni zostan� tylko u�ytkownicy na tej stronie, kt�rzy maj� zaznaczone pole "oznacz"',
  'delete' => 'Usu�',
  'move' => 'Przenie�',
  'copy' => 'Kopiuj',
  'nothing' => 'Nic',
  'to' => 'do', # as in destination
  'from this list' => 'z tej listy',
  'What to do with all users' => 'Co zrobi� ze wszystkimi u�ytkownikami',
  'This will process all users on this list' => 'Przetworzeni zostan� wszyscy u�ytkownicy z listy',
  'do it' => 'wykonaj',
  
  
);
?>