<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'uruchomiono w trybie testowym. Wiadomo�ci nie b�d� wysy�ane. Sprawd� plik konfiguracyjny.',
'The following restrictions have been set by your ISP:' => 'Nast�puj�ce ograniczenia zosta�u ustawione przez Twojego dostawc� Internetu:',
'Script stage' => 'Etap skryptu',
'Finished, Nothing to do' => 'Uko�czono, nie ma nic do zrobienia',
'messages sent in' => 'wiadomo�ci wys�ano w',
'seconds' => 'sekund',
'invalid emails' => 'nieprawid�owych adres�w email',
'emails failed (will retry later)' => 'adres�w, na kt�re nie mozna by�o wys�a� (pr�ba zostanie powt�rzona p�niej)',
'emails unconfirmed (not sent)' => 'niepotwierdzonych adres�w email (nie wys�ano)',
'Warning: script never reached stage 5' => 'Uwaga: skrypt nie osi�gn�� etapu 5',
'This may be caused by a too slow or too busy server' => 'Mo�e to by� spowodowane przez zbyt wolny lub zbyt zaj�ty serwer',


'In safe mode, batches are set to a maximum of 100' => 'W trybie awaryjnym, partie s� ustawione maksymalnie na 100',
'Running in safe mode' => 'uruchomiono w trybie awaryjnym',
'msgs/hr' => 'wiad/godz.',
'Reload required' => 'Konieczne prze�adowanie',
'Finished, All done' => 'Uko�czono, Wszystko zrobione.',
'Script finished, but not all messages have been sent yet.' => 'Skrypt uko�czony ale nie wszystkie wiadomo�ci zosta�y jeszscze wys�ane.',
'Finished this run' => 'Zako�czono to uruchomienie',
'(test)' => '(test)',
'Would have sent' => 'Zosta�oby wys�ane',
'(test)' => '(test)',
'Would have sent' => 'Zosta�oby wys�ane',
'Started' => 'Uruchomiono',
'Processing has been suspended by your ISP, please try again later' => 'Przetwarzanie zosta�o wstrzymane przez dostaw� Internetu, spr�buj p�niej',
'Sending in batches of' => 'Wysy�anie w partiach ',
'emails' => 'emaili',
'This batch will be' => 'W tej partii b�dzie',
'emails, because in the last' => 'emaili, poniewa� jest ostatnia',
'emails were sent' => 'emaili wys�ano',
'Sending in batches of' => 'Wysy�anie w partiach ',
'emails' => 'emaili',
'In the last' => 'W ostatnich',
'seconds more emails were sent' => 'sekundach zosta�o wys�anych wi�cej emaili',
'than is currently allowed per batch' => 'ni� jest to obecnie dozwolone w partii',
'Sent in last run' => 'Wys�ano w ostatnim uruchomieniu',
'Skipped in last run' => 'Pomini�to w ostatnim uruchomieniu',
'Processing has started,' => 'Uruchomiono przetwarzanie,',
'message(s) to process.' => 'wiadomo�ci do przetworzenia.',
'It is safe to click your stop button now, report will be sent by email to' => 'Teraz mo�esz klikn�� przycisk "stop", raport zostanie wys�any poczt� na adres',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Tw�j serwer WWW jest uruchomiony w trybie awaryjnym. Zostaw to okno otwarte. Mo�e ono prze�adowywa� si� kilka razy aby uby�a pewno��, �e wszystkie wiadomo�ci zosta�y wys�ane.',
'Reports will be sent by email to' => 'Raport zostanie wys�any poczt� na adres',
'Processing message' => 'Przetwarzanie wiadomo�ci nr',
'Message' => 'Wiadomo��',
'is an RSS feed for' => 'jest nag��wkiem RSS dla',
'Looking for users' => 'Wyszukiwanie u�ytkownik�w',
'users apply for attributes, now checking lists' => 'wybrane atrybuty u�ytkownika s� odpowiednie, sprawdzanie list',
'No users apply for attributes' => '�aden u�ytkownik nie pasuje do wybranych atrybut�w',
'looking for users who can be excluded from this mailing' => 'Poszukiwanie u�ytkownik�w, kt�rzy mog� zosta� wy��czeni z tego przetwarzania',
'Process Killed by other process' => 'Proces zosta� zako�czony przez inny proces',
'Found them' => 'Znaleziono',
'to process' => 'do przetworzenia',
'No users to process for this batch' => 'Brak u�ytkownik�w do przetworzenia w tej partii',
'batch limit reached' => 'osi�gni�to limit partii',
'Process Killed by other process' => 'Proces zosta� zako�czony przez inny proces',
'Message I was working on has disappeared' => 'Przetwarzana wiadomo�� znikn�a',
'Sending' => 'Wysy�anie',
'It took' => 'Min�o',
'seconds to send' => 'sekund podczas wysy�ania',
'Failed sending to' => 'Nie powiod�o si� wysy�anie do',
'Unconfirmed user' => 'U�ytkownik niepotwierdzony',
'Not sending to' => 'Nie wys�ano do',
'already sent' => 'wys�ano',
'Processed' => 'Przetworzono',
'out of' => 'z',
'Hmmm, No users found to send to' => 'Hmmm, nie znaleziono u�ytkownik�w aby wys�a�',
'It took' => 'Min�o',
'to send this message' => 'podczas wysy�ania tej wiadomo�ci',
'waiting for' => 'oczekiwanie na',
'to make sure we don\'t exceed our limit of' => 'aby by� pewnym, �e nie przekroczymy limitu',
'messages in' => 'wiadomo�ci w',

### new in 2.9.5
'Message Sending has started' => 'Rozsy�anie wiadomo�ci rozpocz�te',
'phplist has started sending the message with subject %s' => 'phplist - rozpocz�to rozsy�anie wiadomo�ci o temacie %s',
'to view the progress of this message, go to %s' => 'aby obejrze� post�p wysy�ania kliknij %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'Ponad 10 razy pr�bowano wys�a� do %s. Pr�by te zosta�y zablokowane poprzez przepustowo�� domeny.',
'Introducing extra delay to decrease throttle failures' => 'Wprowadzanie dodatkowego op�nienia aby obni�y� b��dy przepustowo�ci',
'%s is currently over throttle limit of %d per %d seconds' => '%s jest aktualnie ponad limit przepustowo�ci %d na %d sekund',
'not sending to ' => 'nie wysy�am do ',
'Message Sending has finished' => 'Uko�czono wysy�anie wiadomo�ci',
'phplist has finished sending the message with subject %s' => 'phplist - zako�czono wysy�anie wiadomo�ci o temacie %s',

'Sending of this message has been suspended' => 'Wysy�anie tej wiadomo�ci zosta�o wstrzymane',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Wys�ano mniej niz w partii, wi�c prze�adowuje natychmiast',
'Waiting for %d seconds before reloading' => 'oczekiwanie %d sekund przed prze�adowaniem',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Pozostaw to okno otwarte. Rozpocz��e� przetwarzanie partii, wi�c okno b�dzie si� prze�adowywa�o kilka razy aby wys�a� wiadomo�ci. Raport zostanie wys�any poczt� na adres',

);

?>